DELETE http://localhost:3001/api/persons/69921ee25bcd584d0398622c

###
DELETE http://localhost:3001/api/persons/fasdkfjkladsf

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Helloo1",
  "number": 74981327489123
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Helloo2"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "number": 74981327489123
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Helloo2",
  "number": 74981327489123
}

###

POST https://phonebook-bj8c.onrender.com/api/persons
content-type: application/json

{
  "name": "Helloo4",
  "number": 74981327489123
}

###

DELETE https://phonebook-bj8c.onrender.com/api/persons/2

###

PUT http://localhost:3001/api/persons/6990f4632cc8f1811835b5ae
content-type: application/json

{"name":"Arto Vihavainen","number":"045-1232456"}